### PR TITLE
Added newlines after "raise" (two cases were missing).

### PR DESCRIPTION
**Pull request by bloff**

### CODE REVIEW

**Comment by darkfoxprime** [comment]
Thanks for the fix!  Can you please move this into a feature branch rather than the master branch?

**Comment by bloff** [comment]
I don't understand what you are requesting. Your repository only has one branch currently. Should I create a new branch? If so, what should I name it?

**Comment by darkfoxprime** [comment]
It's only one branch at this instant, but it's standard git practice that all new features and fixes happen in separate "feature" or "topic" branches and then get merged in.

In any case, I'll go ahead and merge this in.  Thanks again for the fix.

**Comment by bloff** [comment]
I didn't know that. Can you tell me how that works exactly? I create a separate branch in my local copy, and then I suggest you merge it to what... 'master'? I cannot make a pull request on your repository on a branch that doesn't exist in your repository (I think!).

**Comment by darkfoxprime** [comment]
The basic idea is that, for every new change you want to make, you create a new (descriptively-named) branch, make your changes and commit them, then open a pull request.  The pull request will automatically be opened against the master branch of the original repo, unless you specify otherwise when you create the pull request.  When the maintainer of the original repo accepts your changes, they will merge the pull request into the master branch.

GitHub calls this process the [GitHub Workflow](https://help.github.com/articles/what-is-a-good-git-workflow/) (in Git, a "workflow" is a model of how multiple contributors interact with a repository)

**Comment by bloff** [comment]
Ah, got it. The purpose is not to soil the master branch in *my own fork*
of the repository. I saw the workflow doc, thank you for explaining.

**Pull request merged**
